# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"LinkGetter": "01_graph.ipynb",
         "GenomeGraph": "01_graph.ipynb",
         "AmbigouosTreeEdge": "02_tree.ipynb",
         "AmbigouosRootNode": "02_tree.ipynb",
         "TremauxTree": "02_tree.ipynb",
         "readTransMap": "03_synteny.ipynb",
         "generateOrder": "03_synteny.ipynb",
         "getIDs": "03_synteny.ipynb",
         "processAccession": "03_synteny.ipynb",
         "recordSegment": "03_synteny.ipynb",
         "addLink": "03_synteny.ipynb",
         "generatePathsLinks": "03_synteny.ipynb",
         "writeLinks": "03_synteny.ipynb",
         "writePath": "03_synteny.ipynb",
         "writeSegmentIDs": "03_synteny.ipynb",
         "readSegmentIDs": "03_synteny.ipynb",
         "pathConvert": "04_utils.ipynb",
         "checkZoomLevels": "04_utils.ipynb",
         "adjustZoomLevels": "04_utils.ipynb",
         "NpEncoder": "04_utils.ipynb",
         "bidict": "04_utils.ipynb",
         "pathFileToPathDict": "04_utils.ipynb",
         "componentTemplate": "05_export.ipynb",
         "chunkTemplate": "05_export.ipynb",
         "rootStructTemplate": "05_export.ipynb",
         "exportToPantograph": "05_export.ipynb",
         "checkLinks": "05_export.ipynb",
         "getMatrixPathElement": "05_export.ipynb",
         "joinComponents": "05_export.ipynb",
         "calcNodeLengths": "05_export.ipynb",
         "initialPathAnalysis": "05_export.ipynb",
         "finaliseBin": "05_export.ipynb",
         "adjustMatrixPathArray": "05_export.ipynb",
         "finaliseComponent": "05_export.ipynb",
         "checkLinksForBreak": "05_export.ipynb",
         "finaliseChunk": "05_export.ipynb",
         "addLinksToComp": "05_export.ipynb",
         "splitforwardInversedNodeComp": "05_export.ipynb",
         "fillLinks": "05_export.ipynb"}

modules = ["__init__.py",
           "graph.py",
           "tree.py",
           "synteny.py",
           "utils.py",
           "export.py"]

doc_url = "//pangraph_constructor"

git_url = "https://gitlab.com/pigrenok/pangraph_constructor/tree/master/"

def custom_doc_links(name): return None
