# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"LinkGetter": "01_graph.ipynb",
         "GenomeGraph": "01_graph.ipynb",
         "AmbigouosTreeEdge": "02_tree.ipynb",
         "AmbigouosRootNode": "02_tree.ipynb",
         "TremauxTree": "02_tree.ipynb",
         "readTransMap": "03_synteny.ipynb",
         "generateOrder": "03_synteny.ipynb",
         "getIDs": "03_synteny.ipynb",
         "processAccession": "03_synteny.ipynb",
         "recordSegment": "03_synteny.ipynb",
         "addLink": "03_synteny.ipynb",
         "generatePathsLinks": "03_synteny.ipynb",
         "writeLinks": "03_synteny.ipynb",
         "writePath": "03_synteny.ipynb",
         "writeSegmentIDs": "03_synteny.ipynb",
         "readSegmentIDs": "03_synteny.ipynb",
         "bidict": "04_utils.ipynb"}

modules = ["__init__.py",
           "graph.py",
           "tree.py",
           "synteny.py",
           "utils.py",
           "export.py"]

doc_url = "//pangraph_constructor"

git_url = "https://gitlab.com/pigrenok/pangraph_constructor/tree/master/"

def custom_doc_links(name): return None
